services:
  AztecBot:
    image: node:20
    container_name: AztecBot
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["sh", "-c", "npm install --include=dev  && npm run start"]
