services:
  Tor:
    image: dperson/torproxy
    container_name: TorProxy
    environment:
      - TZ=Europe/Rome # Imposta la variabile TimeZone per avere l'orario italiano nei logs
    ports:
      - "9050:9050"
    networks:
      - tor-network

networks:
  tor-network:
    name: tor-network
    driver: bridge


